name: Update CISA Known Exploited Vulnerabilities Feed

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  download_cisa_vuln_feed:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download CISA Known Exploited Vulnerabilities Feed
        run: curl -L "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json" > known_exploited_vulnerabilities.json

      - name: Commit and Push if it has updates
        uses: stefanzweifel/git-auto-commit-action@v5

